#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Author: wxnacy(wxnacy@gmail.com)
# Description:

import sys
import os
import subprocess
import pyperclip
import click
from os.path import basename
from shutil import copyfile

PROJECT_NAME='image'
BUCKET_NAME='common'

@click.command()
@click.option('-k', default='', help='Image key name')
@click.argument('filepath')
def run(k, filepath):
    '''上传操作'''
    print(k)
    os.path.dirname
    command_file = sys.argv[0]
    image_dir = os.path.dirname(command_file)
        #  print("Usage: upload_image <filename>")
    #  if len(sys.argv) == 1:
    #  filepath = sys.argv[1]
    filename = basename(filepath)
    to_file = '{}/{}/{}'.format(image_dir, BUCKET_NAME, filename)
    copyfile(filepath, to_file)
    push_file = '{}/push'.format(image_dir)
    #  subprocess.check_call([push_file, image_dir, 'upload {}'.format(filename)])
    msg = 'upload {}'.format(filename)
    p = subprocess.Popen([push_file, image_dir, msg])
    p.wait()
    #  p.communicate()

    url = 'https://raw.githubusercontent.com/wxnacy/{}/master/{}/{}'.format('image',
        'common', filename)

    print('\nImage url is: {}'.format(url))
    print('And it has been copied to the clipboard, you can use it with <ctrl-v>')
    pyperclip.copy(url)

if __name__ == "__main__":
    run()
