#!/usr/bin/env bash

path=$1
msg=${@/$1/}
DIR=`pwd`

if [[ "$DIR" != "$path" && -d $path ]];then
    # echo 'cd'
    cd $path
else
    msg=$@
fi

push(){
    git pull && git add . && git commit -m "${msg}" && git push origin master
}

push
