#!/usr/bin/env bash

project_name=image
dir_name=common
file=$1
filenames=(${file//\// })
echo ${filenames[0]}
echo ${filenames[-1]}

# cp $file $dir_name
# ./push upload $file
# echo "https://raw.githubusercontent.com/wxnacy/${project_name}/master/${dir_name}/${}"



