#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Author: wxnacy(wxnacy@gmail.com)
# Description:

import sys
import os
import subprocess
from os.path import basename
from shutil import copyfile

PROJECT_NAME='image'
BUCKET_NAME='common'

if __name__ == "__main__":
    os.path.dirname
    print(sys.argv)
    command_file = sys.argv[0]
    image_dir = os.path.dirname(command_file)
    print(image_dir)
    if len(sys.argv) == 1:
        print("Usage: upload_image <filename>")
    filepath = sys.argv[1]
    filename = basename(filepath)
    to_file = '{}/{}/{}'.format(image_dir, BUCKET_NAME, filename)
    copyfile(filepath, to_file)
    push_file = '{}/push'.format(image_dir)
    #  subprocess.check_call(['cd', image_dir, '&&', 'ls'])
    #  subprocess.check_call(['ls'])
    subprocess.check_call([push_file, image_dir, 'upload {}'.format(filename)])
    #  subprocess.check_call(['git', 'add', '.'])

    print('https://raw.githubusercontent.com/wxnacy/{}/master/{}/{}'.format('image',
        'common', filename))






